#!/bin/bash

# Exit on error
set -e

# Declare constants
BUILD_DIR="/mnt/c/tmp/daas/build"
DOCKERFILE="Dockerfile.build-rootfs"
NAME="fedora"
OUTFILE="rootfs.tar"
TAG="40"

IMAGE=$NAME:$TAG

if ! which docker; then

    install_script="install.sh"
    url="https://github.com/celluloid-demon/docker-install"

    # Clone
    git clone "$url"

    # Run
    cd docker-install
    sh $install_script

fi

# Initialize
mkdir -p $BUILD_DIR

# Build image
docker build --file $DOCKERFILE --tag $NAME:$TAG .

# Spin up container
docker run -t $NAME:$TAG bash -c ls /

# Evade UNC complaints
cd $BUILD_DIR

# Export container
[ -f "${BUILD_DIR}/${OUTFILE}" ] && rm "${BUILD_DIR}/${OUTFILE}"
docker export -o $OUTFILE "$(docker container ls -a | grep -i $IMAGE | awk '{print $1}')"

# Prune unused containers
docker container prune --force

# Remove old build images but keep cached layers
docker image rm --force $IMAGE
