#!/bin/bash

# Exit on error
set -e

# Declare constants
EXPORT_DIR="export"
NAME="fedora-desktop-full"
OUTFILE="rootfs.tar"
TAG="40"

IMAGE=$NAME:$TAG

if ! which docker; then

    install_script="install.sh"
    url="https://github.com/celluloid-demon/docker-install"

    # Clone
    git clone "$url"

    # Run
    cd docker-install
    sh $install_script

fi

# Initialize
mkdir -p $EXPORT_DIR

# Spin up container
docker run -t $IMAGE ls /

# Export container
docker export -o ${EXPORT_DIR}/${OUTFILE} "$(docker container ls -a | grep -i $IMAGE | awk '{print $1}')"

# Prune unused containers
docker container prune --force

# Remove old build images and cached layers
docker image rm --force $IMAGE
docker image rm --force fedora-desktop-core:40
docker system prune --force
