#!/bin/bash

# Exit on error
set -e

# Declare constants
EXPORT_DIR=export
DISTRO_NAME=Fedora
INSTALL_LOCATION="/mnt/c/Users/Jonathan/Applications/Fedora"
INSTALL_TAR_FILE=rootfs.tar
LAUNCHER="Fedora (Desktop).lnk"
TMP=/mnt/c/tmp
WIN_HOME=/mnt/c/Users/Jonathan

WIN_TMP='C:\tmp'
WIN_INSTALL_LOCATION='C:\Users\Jonathan\Applications\Fedora'

# Exit if rootfs archive missing
[ ! -f ${EXPORT_DIR}/${INSTALL_TAR_FILE}  ] && echo "${EXPORT_DIR}/${INSTALL_TAR_FILE} not detected, exiting..." && exit 1

# Initialize
mkdir -p "$INSTALL_LOCATION"
mkdir -p "$TMP"

# "Flash" launcher
[ ! -f "${WIN_HOME}/Desktop/${LAUNCHER}" ] && cp "resources/${LAUNCHER}" ${WIN_HOME}/Desktop/

# Evade UNC complaints
echo "Copying working files to tmp directory..."
cp ${EXPORT_DIR}/${INSTALL_TAR_FILE} ${TMP}/
cd $TMP

# wsl --import <DistroName> <InstallLocation> <InstallTarFile>
cmd.exe /c wsl --import $DISTRO_NAME $WIN_INSTALL_LOCATION ${INSTALL_TAR_FILE}

# Cleanup
rm ${TMP}/${INSTALL_TAR_FILE}
