#!/bin/bash

FETCH=0

[ $FETCH -eq 1 ] && powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\fetch-distro.ps1"

if [ -z $(pidof xfce4-session) ]; then

    export HOST_IP=$(ip route list default | awk '{print $3}')
    export DISPLAY=$HOST_IP:0
    export PULSE_SERVER=tcp:$HOST_IP

    cmd.exe /c '.\xfce.xlaunch'
    cmd.exe /c 'C:\pulseaudio\bin\pulseaudio.exe' &

    # /mnt/c/pulseaudio/bin/pulseaudio.exe &

    xfwm4_config="${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"

    # Fix a bug with compositing not loading correctly, symptom is choppy desktop UI (it initializes as expected tho; workaround is thus force it to re-initialize)
    sed -i '/property name=\"use_compositing\"/d' "$xfwm4_config"
    
    # todo clean this up a bit to just use wait command on startxfce4 pid?
    # NOTE: At this point, do NOT start in background (pkill logic will run when user logs out)
    cd "$HOME" && startxfce4
    
    pkill '(gpg|ssh)-agent'
    taskkill.exe /IM pulseaudio.exe /F
    taskkill.exe /IM vcxsrv.exe /F

fi
