#!/bin/bash

# Exit on error
set -e

FILE="get-docker.sh"
TMP="/mnt/c/tmp/daas"
URL="https://get.docker.com"

if ! which docker; then

    # Initialize
    mkdir -p $TMP && cd $TMP

    # Download
    curl -fsSL $URL -o $FILE

    # Backup
    mv $FILE ${FILE}.bak

    # Remove check for WSL
    sed '/if is_wsl; then/,/fi/d' ${FILE}.bak > $FILE

    # Run
    eval $FILE

fi
