#!/bin/bash

# NOTE: You can run this in whatever distro you want. The sed-statement will allow us to bypass the WSL check and install the docker engine directly in our distro.

# NOTE: For this purpose you can temporarily open your distro like this: `wsl -d ubuntu`

FILE="get-docker.sh"
TMP="tmp"
URL="https://get.docker.com"

MODIFIED_FILE="modified-${FILE}"

init() {

    mkdir -p "./${TMP}"

}

if ! which docker; then

    init

    curl -fsSL "$URL" -o "./${FILE}"

    sed '/if is_wsl; then/,/fi/d' "./${FILE}" > "./${MODIFIED_FILE}"

    eval "./${MODIFIED_FILE}"

fi
