#!/bin/bash

# Exit on error
set -e

# Declare constants
BUILD_DIR=/mnt/c/tmp/daas/build
DISTRO_NAME=Fedora
INSTALL_TAR_FILE=rootfs.tar
LAUNCHER="Fedora (Desktop.lnk)"
WIN_HOME=/mnt/c/Users/Jonathan

WIN_BUILD_DIR='C:\tmp\daas\build'
WIN_INSTALL_LOCATION='C:\Fedora'

# Initialize
[ ! -f ${BUILD_DIR}/${INSTALL_TAR_FILE}  ] && echo "${BUILD_DIR}/${INSTALL_TAR_FILE} not detected, exiting..." && exit 1
[ ! -f "${WIN_HOME}/Desktop/${LAUNCHER}" ] && cp "$LAUNCHER" ${WIN_HOME}/Desktop/

# Evade UNC complaints
cd $BUILD_DIR

# wsl --import <DistroName> <InstallLocation> <InstallTarFile>
cmd.exe /c wsl --import $DISTRO_NAME $WIN_INSTALL_LOCATION ${WIN_BUILD_DIR}/${INSTALL_TAR_FILE}

# Cleanup
rm ${BUILD_DIR}/${INSTALL_TAR_FILE}
